namespace APIProject.DTOs
{
    public class CommandCreateDTO
    {
        // ID need not be supplied by the API client, since it is generated by 
        // the database; the other 3 fields must still be supplied by the HTTP request
        // public int Id { get; set; }

        public string HowTo { get; set; }

        public string Line { get; set; }

        public string Platform { get; set; }
    }
}