using System.ComponentModel.DataAnnotations;

namespace APIProject.DTOs
{
    public class CommandCreateDTO
    {
        // ID need not be supplied by the API client, since it is generated by 
        // the database; the other 3 fields must still be supplied by the HTTP request
        // public int Id { get; set; }

        // data annotations added to allow server to throw 400 error codes,
        // in cases where the JSON body of the HTTP POST request is incorrectly formatted

        [Required]
        [MaxLength(250)]
        public string HowTo { get; set; }

        [Required]
        public string Line { get; set; }

        [Required]
        public string Platform { get; set; }
    }
}